stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - before_ci_script

docker-build:
  stage: build
  script:
    - docker_build_fe_script
  after_script:
    - after_ci_fe_script
  tags:
    - global-runner

  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^ci /
      - $CI_COMMIT_REF_NAME == "dev"
      - $CI_COMMIT_REF_NAME == "dev-docker"
      - $CI_COMMIT_REF_NAME == "docker"
      - $CI_PIPELINE_SOURCE == "web"
      - $CI_PIPELINE_SOURCE == "api"
