// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasePreview: typeof import('./src/components/preview/BasePreview.vue')['default']
    BorderEditor: typeof import('./src/components/editors/BorderEditor.vue')['default']
    Button: typeof import('./src/components/button/index.vue')['default']
    ButtonEditor: typeof import('./src/components/editors/ButtonEditor.vue')['default']
    ColorEditor: typeof import('./src/components/editors/ColorEditor.vue')['default']
    DialogEditor: typeof import('./src/components/editors/DialogEditor.vue')['default']
    EditComp: typeof import('./src/components/edit-comp/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElementPlusDemo: typeof import('./src/components/ElementPlusDemo.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    FontEditor: typeof import('./src/components/editors/FontEditor.vue')['default']
    FormEditor: typeof import('./src/components/editors/FormEditor.vue')['default']
    InputEditor: typeof import('./src/components/editors/InputEditor.vue')['default']
    MarginEditor: typeof import('./src/components/editors/MarginEditor.vue')['default']
    PropertyEditor: typeof import('./src/components/editors/PropertyEditor.vue')['default']
    RadiusEditor: typeof import('./src/components/editors/RadiusEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectEditor: typeof import('./src/components/editors/SelectEditor.vue')['default']
    SizeEditor: typeof import('./src/components/editors/SizeEditor.vue')['default']
    TableEditor: typeof import('./src/components/editors/TableEditor.vue')['default']
    TabsEditor: typeof import('./src/components/editors/TabsEditor.vue')['default']
    ThemeEditor: typeof import('./src/components/ThemeEditor.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}

export {}
